// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ided.proto

package com.github.stepancheg.rustide.client.proto;

public final class IdedProtos {
  private IdedProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .ided.Request.Ping ping = 1;
    /**
     * <code>optional .ided.Request.Ping ping = 1;</code>
     */
    boolean hasPing();
    /**
     * <code>optional .ided.Request.Ping ping = 1;</code>
     */
    com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping getPing();
    /**
     * <code>optional .ided.Request.Ping ping = 1;</code>
     */
    com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder getPingOrBuilder();

    // optional .ided.Request.Unknown unknown_command = 999;
    /**
     * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
     */
    boolean hasUnknownCommand();
    /**
     * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
     */
    com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown getUnknownCommand();
    /**
     * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
     */
    com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder getUnknownCommandOrBuilder();
  }
  /**
   * Protobuf type {@code ided.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = ping_.toBuilder();
              }
              ping_ = input.readMessage(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ping_);
                ping_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 7994: {
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = unknownCommand_.toBuilder();
              }
              unknownCommand_ = input.readMessage(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(unknownCommand_);
                unknownCommand_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public interface PingOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code ided.Request.Ping}
     */
    public static final class Ping extends
        com.google.protobuf.GeneratedMessage
        implements PingOrBuilder {
      // Use Ping.newBuilder() to construct.
      private Ping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Ping(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Ping defaultInstance;
      public static Ping getDefaultInstance() {
        return defaultInstance;
      }

      public Ping getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Ping(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder.class);
      }

      public static com.google.protobuf.Parser<Ping> PARSER =
          new com.google.protobuf.AbstractParser<Ping>() {
        public Ping parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ping(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Ping> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ided.Request.Ping}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Ping_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Ping_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder.class);
        }

        // Construct using com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Ping_descriptor;
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping getDefaultInstanceForType() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance();
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping build() {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping buildPartial() {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping result = new com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping) {
            return mergeFrom((com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping other) {
          if (other == com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ided.Request.Ping)
      }

      static {
        defaultInstance = new Ping(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ided.Request.Ping)
    }

    public interface UnknownOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code ided.Request.Unknown}
     *
     * <pre>
     * for debugging
     * </pre>
     */
    public static final class Unknown extends
        com.google.protobuf.GeneratedMessage
        implements UnknownOrBuilder {
      // Use Unknown.newBuilder() to construct.
      private Unknown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Unknown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Unknown defaultInstance;
      public static Unknown getDefaultInstance() {
        return defaultInstance;
      }

      public Unknown getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Unknown(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Unknown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Unknown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder.class);
      }

      public static com.google.protobuf.Parser<Unknown> PARSER =
          new com.google.protobuf.AbstractParser<Unknown>() {
        public Unknown parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Unknown(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Unknown> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ided.Request.Unknown}
       *
       * <pre>
       * for debugging
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Unknown_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Unknown_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder.class);
        }

        // Construct using com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_Unknown_descriptor;
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown getDefaultInstanceForType() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance();
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown build() {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown buildPartial() {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown result = new com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown) {
            return mergeFrom((com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown other) {
          if (other == com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ided.Request.Unknown)
      }

      static {
        defaultInstance = new Unknown(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ided.Request.Unknown)
    }

    private int bitField0_;
    // optional .ided.Request.Ping ping = 1;
    public static final int PING_FIELD_NUMBER = 1;
    private com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping ping_;
    /**
     * <code>optional .ided.Request.Ping ping = 1;</code>
     */
    public boolean hasPing() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ided.Request.Ping ping = 1;</code>
     */
    public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping getPing() {
      return ping_;
    }
    /**
     * <code>optional .ided.Request.Ping ping = 1;</code>
     */
    public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder getPingOrBuilder() {
      return ping_;
    }

    // optional .ided.Request.Unknown unknown_command = 999;
    public static final int UNKNOWN_COMMAND_FIELD_NUMBER = 999;
    private com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown unknownCommand_;
    /**
     * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
     */
    public boolean hasUnknownCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
     */
    public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown getUnknownCommand() {
      return unknownCommand_;
    }
    /**
     * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
     */
    public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder getUnknownCommandOrBuilder() {
      return unknownCommand_;
    }

    private void initFields() {
      ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance();
      unknownCommand_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, ping_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(999, unknownCommand_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ping_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(999, unknownCommand_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.stepancheg.rustide.client.proto.IdedProtos.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ided.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.stepancheg.rustide.client.proto.IdedProtos.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.rustide.client.proto.IdedProtos.Request.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Builder.class);
      }

      // Construct using com.github.stepancheg.rustide.client.proto.IdedProtos.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPingFieldBuilder();
          getUnknownCommandFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pingBuilder_ == null) {
          ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance();
        } else {
          pingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (unknownCommandBuilder_ == null) {
          unknownCommand_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance();
        } else {
          unknownCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Request_descriptor;
      }

      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request getDefaultInstanceForType() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.Request.getDefaultInstance();
      }

      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request build() {
        com.github.stepancheg.rustide.client.proto.IdedProtos.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request buildPartial() {
        com.github.stepancheg.rustide.client.proto.IdedProtos.Request result = new com.github.stepancheg.rustide.client.proto.IdedProtos.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (pingBuilder_ == null) {
          result.ping_ = ping_;
        } else {
          result.ping_ = pingBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (unknownCommandBuilder_ == null) {
          result.unknownCommand_ = unknownCommand_;
        } else {
          result.unknownCommand_ = unknownCommandBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.stepancheg.rustide.client.proto.IdedProtos.Request) {
          return mergeFrom((com.github.stepancheg.rustide.client.proto.IdedProtos.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.stepancheg.rustide.client.proto.IdedProtos.Request other) {
        if (other == com.github.stepancheg.rustide.client.proto.IdedProtos.Request.getDefaultInstance()) return this;
        if (other.hasPing()) {
          mergePing(other.getPing());
        }
        if (other.hasUnknownCommand()) {
          mergeUnknownCommand(other.getUnknownCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.stepancheg.rustide.client.proto.IdedProtos.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.stepancheg.rustide.client.proto.IdedProtos.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .ided.Request.Ping ping = 1;
      private com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder> pingBuilder_;
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public boolean hasPing() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping getPing() {
        if (pingBuilder_ == null) {
          return ping_;
        } else {
          return pingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public Builder setPing(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ping_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public Builder setPing(
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          ping_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public Builder mergePing(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping value) {
        if (pingBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              ping_ != com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance()) {
            ping_ =
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.newBuilder(ping_).mergeFrom(value).buildPartial();
          } else {
            ping_ = value;
          }
          onChanged();
        } else {
          pingBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.getDefaultInstance();
          onChanged();
        } else {
          pingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder getPingBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder getPingOrBuilder() {
        if (pingBuilder_ != null) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          return ping_;
        }
      }
      /**
       * <code>optional .ided.Request.Ping ping = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Ping.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.PingOrBuilder>(
                  ping_,
                  getParentForChildren(),
                  isClean());
          ping_ = null;
        }
        return pingBuilder_;
      }

      // optional .ided.Request.Unknown unknown_command = 999;
      private com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown unknownCommand_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder> unknownCommandBuilder_;
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public boolean hasUnknownCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown getUnknownCommand() {
        if (unknownCommandBuilder_ == null) {
          return unknownCommand_;
        } else {
          return unknownCommandBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public Builder setUnknownCommand(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown value) {
        if (unknownCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          unknownCommand_ = value;
          onChanged();
        } else {
          unknownCommandBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public Builder setUnknownCommand(
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder builderForValue) {
        if (unknownCommandBuilder_ == null) {
          unknownCommand_ = builderForValue.build();
          onChanged();
        } else {
          unknownCommandBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public Builder mergeUnknownCommand(com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown value) {
        if (unknownCommandBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              unknownCommand_ != com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance()) {
            unknownCommand_ =
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.newBuilder(unknownCommand_).mergeFrom(value).buildPartial();
          } else {
            unknownCommand_ = value;
          }
          onChanged();
        } else {
          unknownCommandBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public Builder clearUnknownCommand() {
        if (unknownCommandBuilder_ == null) {
          unknownCommand_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.getDefaultInstance();
          onChanged();
        } else {
          unknownCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder getUnknownCommandBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUnknownCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder getUnknownCommandOrBuilder() {
        if (unknownCommandBuilder_ != null) {
          return unknownCommandBuilder_.getMessageOrBuilder();
        } else {
          return unknownCommand_;
        }
      }
      /**
       * <code>optional .ided.Request.Unknown unknown_command = 999;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder> 
          getUnknownCommandFieldBuilder() {
        if (unknownCommandBuilder_ == null) {
          unknownCommandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.Unknown.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Request.UnknownOrBuilder>(
                  unknownCommand_,
                  getParentForChildren(),
                  isClean());
          unknownCommand_ = null;
        }
        return unknownCommandBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ided.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ided.Request)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .ided.Response.Ping ping = 1;
    /**
     * <code>optional .ided.Response.Ping ping = 1;</code>
     */
    boolean hasPing();
    /**
     * <code>optional .ided.Response.Ping ping = 1;</code>
     */
    com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping getPing();
    /**
     * <code>optional .ided.Response.Ping ping = 1;</code>
     */
    com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder getPingOrBuilder();
  }
  /**
   * Protobuf type {@code ided.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = ping_.toBuilder();
              }
              ping_ = input.readMessage(com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ping_);
                ping_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.stepancheg.rustide.client.proto.IdedProtos.Response.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public interface PingOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code ided.Response.Ping}
     */
    public static final class Ping extends
        com.google.protobuf.GeneratedMessage
        implements PingOrBuilder {
      // Use Ping.newBuilder() to construct.
      private Ping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Ping(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Ping defaultInstance;
      public static Ping getDefaultInstance() {
        return defaultInstance;
      }

      public Ping getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Ping(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_Ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder.class);
      }

      public static com.google.protobuf.Parser<Ping> PARSER =
          new com.google.protobuf.AbstractParser<Ping>() {
        public Ping parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ping(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Ping> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ided.Response.Ping}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_Ping_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_Ping_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder.class);
        }

        // Construct using com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_Ping_descriptor;
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping getDefaultInstanceForType() {
          return com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance();
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping build() {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping buildPartial() {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping result = new com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping) {
            return mergeFrom((com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping other) {
          if (other == com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ided.Response.Ping)
      }

      static {
        defaultInstance = new Ping(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ided.Response.Ping)
    }

    private int bitField0_;
    // optional .ided.Response.Ping ping = 1;
    public static final int PING_FIELD_NUMBER = 1;
    private com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping ping_;
    /**
     * <code>optional .ided.Response.Ping ping = 1;</code>
     */
    public boolean hasPing() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ided.Response.Ping ping = 1;</code>
     */
    public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping getPing() {
      return ping_;
    }
    /**
     * <code>optional .ided.Response.Ping ping = 1;</code>
     */
    public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder getPingOrBuilder() {
      return ping_;
    }

    private void initFields() {
      ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, ping_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ping_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.stepancheg.rustide.client.proto.IdedProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.stepancheg.rustide.client.proto.IdedProtos.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ided.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.stepancheg.rustide.client.proto.IdedProtos.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.stepancheg.rustide.client.proto.IdedProtos.Response.class, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Builder.class);
      }

      // Construct using com.github.stepancheg.rustide.client.proto.IdedProtos.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPingFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pingBuilder_ == null) {
          ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance();
        } else {
          pingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.internal_static_ided_Response_descriptor;
      }

      public com.github.stepancheg.rustide.client.proto.IdedProtos.Response getDefaultInstanceForType() {
        return com.github.stepancheg.rustide.client.proto.IdedProtos.Response.getDefaultInstance();
      }

      public com.github.stepancheg.rustide.client.proto.IdedProtos.Response build() {
        com.github.stepancheg.rustide.client.proto.IdedProtos.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.stepancheg.rustide.client.proto.IdedProtos.Response buildPartial() {
        com.github.stepancheg.rustide.client.proto.IdedProtos.Response result = new com.github.stepancheg.rustide.client.proto.IdedProtos.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (pingBuilder_ == null) {
          result.ping_ = ping_;
        } else {
          result.ping_ = pingBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.stepancheg.rustide.client.proto.IdedProtos.Response) {
          return mergeFrom((com.github.stepancheg.rustide.client.proto.IdedProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.stepancheg.rustide.client.proto.IdedProtos.Response other) {
        if (other == com.github.stepancheg.rustide.client.proto.IdedProtos.Response.getDefaultInstance()) return this;
        if (other.hasPing()) {
          mergePing(other.getPing());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.stepancheg.rustide.client.proto.IdedProtos.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.stepancheg.rustide.client.proto.IdedProtos.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .ided.Response.Ping ping = 1;
      private com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder> pingBuilder_;
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public boolean hasPing() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping getPing() {
        if (pingBuilder_ == null) {
          return ping_;
        } else {
          return pingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public Builder setPing(com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ping_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public Builder setPing(
          com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          ping_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public Builder mergePing(com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping value) {
        if (pingBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              ping_ != com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance()) {
            ping_ =
              com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.newBuilder(ping_).mergeFrom(value).buildPartial();
          } else {
            ping_ = value;
          }
          onChanged();
        } else {
          pingBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          ping_ = com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.getDefaultInstance();
          onChanged();
        } else {
          pingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder getPingBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      public com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder getPingOrBuilder() {
        if (pingBuilder_ != null) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          return ping_;
        }
      }
      /**
       * <code>optional .ided.Response.Ping ping = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.Ping.Builder, com.github.stepancheg.rustide.client.proto.IdedProtos.Response.PingOrBuilder>(
                  ping_,
                  getParentForChildren(),
                  isClean());
          ping_ = null;
        }
        return pingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ided.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ided.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ided_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ided_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ided_Request_Ping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ided_Request_Ping_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ided_Request_Unknown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ided_Request_Unknown_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ided_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ided_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ided_Response_Ping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ided_Response_Ping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nided.proto\022\004ided\"o\n\007Request\022 \n\004ping\030\001 " +
      "\001(\0132\022.ided.Request.Ping\022/\n\017unknown_comma" +
      "nd\030\347\007 \001(\0132\025.ided.Request.Unknown\032\006\n\004Ping" +
      "\032\t\n\007Unknown\"5\n\010Response\022!\n\004ping\030\001 \001(\0132\023." +
      "ided.Response.Ping\032\006\n\004PingB8\n*com.github" +
      ".stepancheg.rustide.client.protoB\nIdedPr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ided_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ided_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ided_Request_descriptor,
              new java.lang.String[] { "Ping", "UnknownCommand", });
          internal_static_ided_Request_Ping_descriptor =
            internal_static_ided_Request_descriptor.getNestedTypes().get(0);
          internal_static_ided_Request_Ping_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ided_Request_Ping_descriptor,
              new java.lang.String[] { });
          internal_static_ided_Request_Unknown_descriptor =
            internal_static_ided_Request_descriptor.getNestedTypes().get(1);
          internal_static_ided_Request_Unknown_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ided_Request_Unknown_descriptor,
              new java.lang.String[] { });
          internal_static_ided_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ided_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ided_Response_descriptor,
              new java.lang.String[] { "Ping", });
          internal_static_ided_Response_Ping_descriptor =
            internal_static_ided_Response_descriptor.getNestedTypes().get(0);
          internal_static_ided_Response_Ping_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ided_Response_Ping_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
